version: '3'

services:
    postgresql:
        container_name: postgresql
    image: postgres:latest
    volumes:
        - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
        - ./data/postgresql/data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
        POSTGRES_PASSWORD: '123456'
    networks:
      - common_2
    restart: always
networks:
    common_2: