version: '3'

services:
    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
        user: "${UID_GID}"
        ports:
            - "${REDIS_PORTS}"
        networks:
            - common
        restart: always
    postgresql:
        container_name: postgresql
        image: postgres:alpine
        volumes:
            - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
            #  You need to create data/postgresql/pgdata folder manually or this will error
            - ./data/postgresql/pgdata:/var/lib/postgresql/data
            - /etc/passwd:/etc/passwd:ro
            - ./logs/postgresql:/postgres_log
        user: "${UID_GID}"
        command: postgres -c config_file=/etc/postgresql.conf
        ports:
            - "${POSTGRES_PORTS}"
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
        networks:
            - common
        restart: always
networks:
    common:
