version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        volumes:
            - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
            - ./data/postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        command: postgres -c config_file=/etc/postgresql.conf
        environment:
            POSTGRES_PASSWORD: '123456'
        networks:
            - common
        restart: always
    mongo:
        container_name: mongo
        image: mongo:latest
        volumes:
            - ./data/mongo:/data/db
            - ./logs/mongo:/var/log/mongodb
        user: "${UID_GID}"
        ports:
            - "27017:27017"
        networks:
            - common
        restart: always
    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
            - ./logs/redis:/var/log/redis
        user: "${UID_GID}"
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        user: "${UID_GID}"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
        networks:
            - common
        restart: always
networks:
    common: