version: '3.7'

services:
  database:
    container_name: wordpress_database
    image: mysql
    user: 1000:1000
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - wordpress-network
  application:
    container_name: wordpress_application
    image: wordpress
    ports:
      - 80:80
#    volumes:
#      - ./src:/var/www/html
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=prx
      - WORDPRESS_DEBUG=1
    networks:
      - wordpress-network
networks:
  wordpress-network:
    driver: bridge
