version: '3'

services:
    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
        user: "${UID_GID}"
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        user: "${UID_GID}"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
        networks:
            - common
        restart: always
networks:
    common:
