version: '3'

services:
    postgresql:
        container_name: postgresql
        image: postgres:alpine
        volumes:
            - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
            #  You need to create data/postgresql/pgdata folder manually or this will error
            - ./data/postgresql/pgdata:/var/lib/postgresql/data
            - /etc/passwd:/etc/passwd:ro
            - ./logs/postgresql:/postgres_log
        user: "${UID_GID}"
        command: postgres -c config_file=/etc/postgresql.conf
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: '123456'
        networks:
            - common
        restart: always
networks:
    common:
