version: '3'

services:
    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
        user: "${UID_GID}"
        ports:
            - "${REDIS_PORTS}"
        networks:
            - common
        restart: always
    mongo:
        container_name: mongo
        image: mongo:latest
        volumes:
#            - ./config/mongo/mongod.conf:/etc/mongod.conf
            - ./data/mongo:/data/db
            - ./logs/mongo:/var/log/mongodb
        user: "${UID_GID}"
        ports:
            - "${MONGO_PORTS}"
        command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - common
        restart: always
networks:
    common:
