version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        volumes:
#            - ./config/mongo/mongod.conf:/etc/mongod.conf
            - ./data/mongo:/data/db
            - ./logs/mongo:/var/log/mongodb
        user: "${UID_GID}"
        ports:
            - "27017:27017"
        command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        networks:
            - common
        restart: always
    redis:
        container_name: redis
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./data/redis:/data
        user: "${UID_GID}"
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always
networks:
    common:
