version: '3'

services:
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
        ports:
            - "8080:80"
        restart: always
        networks:
            - databases_common
networks:
    databases_common:
        external: true
