version: '2'
# run "docker volume create --name data -d local" befor start working

services:
    # web:
    #     restart: always
    #     build:
    #         context: ./image/passenger_ruby
    #     # env_file: ./config/enviroment/passenger_ruby/.env
    #     volumes:
    #         # mount code folder
    #         - ~/public_html:/var/www/html
    #         # Custom vhost
    #         - ./config/nginx/conf.d:/etc/nginx/conf.d
    #         - ./config/nginx/main.d:/etc/nginx/main.d
    #         # nginx log
    #         - ./log/nginx:/var/log/nginx
    #     ports:
    #         - "80:80"
    #     links:
    #         - postgres
            # - redis
    postgres:
        # volumes:
        #     - ./log/postgres:/logs
        build:
            context: ./image/postgres9.5
        ports:
            - "5432:5432"
# volumes:
#     data:
#         external: true
# run "docker volume rm data" after finish work
