version: '3'

services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
            PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
        ports:
            - "${PGADMIN_PORTS}"
        restart: always
        networks:
            - databases_common
networks:
    databases_common:
        external: true
