version: '3'

services:
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: ${PMA_HOST}
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        ports:
            - "${PMA_PORTS}"
        restart: always
        networks:
            - databases_common
networks:
    databases_common:
        external: true
