version: '3.7'

services:
  # The Application
  application:
    image: ${APPLICATION_IMAGE_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_CODE_PATH_CONTAINER}/storage
    build:
      context: .
      dockerfile: ./config/application/Dockerfile
      args:
        - TZ=${TIMEZONE}
        - ENVIRONMENT=${ENVIRONMENT}
        # xdebug
        - WITH_XDEBUG=${WITH_XDEBUG}
        - REMOTE_PORT=${REMOTE_PORT}
        - REMOTE_HOST=${REMOTE_HOST}
        - IDE_KEY=${IDE_KEY}
        # application
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
        - APP_CODE_PATH_HOST=${APP_CODE_PATH_HOST}
    networks:
      - php-network

  # The Web Server
  webserver:
    image: ${WEBSERVER_IMAGE_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}_webserver
    volumes:
      - ./${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    build:
      context: .
      dockerfile: ./config/webserver/Dockerfile
      args:
        - TZ=${TIMEZONE}
        - APP_CODE_PATH_PUBLIC=${APP_CODE_PATH_PUBLIC}
        - FILE_CONFIG_NGINX=${FILE_CONFIG_NGINX}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
        - APP_CODE_PATH_HOST=${APP_CODE_PATH_HOST}
    ports:
      - ${PORT_MAPPING_WEBSERVER}
    depends_on:
      - application
    networks:
      - php-network

  # The Database
  database:
    image: mysql
    container_name: ${COMPOSE_PROJECT_NAME}_database
    user: "${UID_GID}"
    volumes:
      - ./config/database/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${PORT_MAPPING_MYSQL}
    networks:
      - php-network

  # redis
  cache:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_cache
    user: "${UID_GID}"
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - ${PORT_MAPPING_REDIS}
    volumes:
      - ./data/redis:/data
    networks:
      - php-network
networks:
  php-network:
    driver: ${NETWORKS_DRIVER}
